# Generated by Django 2.2 on 2019-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_1',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
