# Generated by Django 2.2 on 2019-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack_10',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_2',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_3',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_4',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_5',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_6',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_7',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_8',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack_9',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField()),
                ('sensor', models.IntegerField()),
                ('sensor_type', models.CharField(max_length=15)),
                ('sensor_value', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='datetime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack_1',
            name='datetime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smoke',
            name='datetime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
